# JVM Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true

# AndroidX проект не использует — сборка чистого WebView-клиента без зависимостей.
android.useAndroidX=false
android.enableJetifier=false
# Непереходный R-класс: меньше работа компилятора, быстрее сборка.
android.nonTransitiveRClass=true
